### ISSUE TITLE
push missing?

### ISSUE THREAD

**Issue by mmoll** [stschulte/puppet-rpmkey#3]
Hello,

I wanted to do a PR to update the metadata, however, it seems v1.0.1 is only available on Puppetforge and the update was not pushed here.

**Comment by stschulte** [comment]
@mmoll You are absolutely right! I did run `git push --tags origin` but having `--tags` in the commandline apparently makes the branch name mandatory in case you also want to push the master branch together with your tags.

The git tag `v1.0.1` represents the `1.0.1` release on the forge. Thanks for the information! Have a great day!
